services:
  insurance-rest: &insurance_rest
    container_name: "insurance-rest"
    build:
      context: ./
      dockerfile: Dockerfile-dev
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - postgres
    networks:
      - insura_net

  sneakers:
    <<: *insurance_rest
    container_name: "sneakers"
    ports:
      - 3001:3000
    command: ["rake", "sneakers:run"]
    networks:
    - insura_net

  postgres:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ~/tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=S3cret
      - PGUSER=insura_usr
      - POSTGRES_DB=insura_db
      - POSTGRES_HOST=postgres
    networks:
      - insura_net

networks:
  insura_net:
    name: insurance-network
    external: true
