FROM ruby:3.3.0
ARG USER_ID=1000

RUN mkdir /app
WORKDIR /app
COPY Gemfile ./
COPY Gemfile.lock ./

RUN apt install libpq-dev

RUN bundle install
COPY . .

RUN useradd guilherme --uid ${USER_ID} --create-home --shel /bin/bash && \
     chown -R guilherme:guilherme .

USER guilherme:guilherme
EXPOSE 3000

CMD ["rails", "s", "-b", "0.0.0.0"]
